on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Compile rootfs
    runs-on:
      group: Default
      labels: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for build (Apt)
        run: |
          sudo env DEBIAN_FRONTEND=noninteractive apt update -y && \
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y libarchive-tools
      - name: Build
        run: |
          make
          make clean
      - uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retention-days: 5
          path: |
            rootfs.tar.gz

  deploy:
    needs: [ build ]
    name: Publish on Github
    runs-on:
      group: Default
      labels: self-hosted
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          path: |
            rootfs.tar.gz
      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
