on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  avoidRedundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Compile rootfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for build (Apt)
        run: |
          sudo env DEBIAN_FRONTEND=noninteractive apt update -y && \
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y libarchive-tools
      - name: Build
        run: |
          make
          make clean
      - uses: actions/upload-artifact@v2
        with:
          retention-days: 5
          path: |
            rootfs.tar.gz

  deploy:
    needs: [ build ]
    name: Publish on Github
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: |
            rootfs.tar.gz
      - name: Upload the release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
